
# cookies (for yt-dlp / streaming)
cookies=yes
ytdl-raw-options=cookies-from-browser=chrome


### Audio and Subtitles ###

slang=en,eng,English
alang=en,eng

sub-auto=all
sub-fix-timing=yes
sub-file-paths=sub;subs;subtitles
sub-file-paths-append=subtitles
demuxer-mkv-subtitle-preroll=yes

sub-blur=0.5
sub-scale=0.7
sub-margin-y=60
sub-color='#d6ffffff'
sub-shadow-offset=5.0
sub-font=Clear Sans Bold
sub-back-color='#00000000'
sub-shadow-color='#00000000'
sub-outline-color='#266a678c'
sub-ass-override=yes
blend-subtitles=yes

volume-max=150
audio-file-auto=fuzzy
audio-normalize-downmix=yes


### General ###

keep-open=yes
save-position-on-quit=yes
ontop=yes


### uosc ###

osc=no
osd-bar=no
border=no
