keybindings:
  back: ctrl-q
  next_page: null
  previous_page: null
  jump_to_start: null
  jump_to_end: null
  jump_to_album: a
  jump_to_artist_album: A
  jump_to_context: o
  manage_devices: d
  decrease_volume: '-'
  increase_volume: +
  toggle_playback: ' '
  seek_backwards: <
  seek_forwards: '>'
  next_track: n
  previous_track: p
  help: '?'
  shuffle: ctrl-s
  repeat: r
  search: /
  submit: null
  copy_song_url: c
  copy_album_url: C
  audio_analysis: v
  basic_view: null
  add_item_to_queue: z
behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  volume_percent: 100
  tick_rate_milliseconds: 250
  enable_text_emphasis: true
  show_loading_indicator: true
  enforce_wide_search_bar: false
  enable_global_song_count: true
  shuffle_enabled: false
  liked_icon: ♥
  shuffle_icon: 🔀
  repeat_track_icon: 🔂
  repeat_context_icon: 🔁
  playing_icon: ▶
  paused_icon: ⏸
  set_window_title: true
  visualizer_style: Equalizer
theme:
  active: Black
  banner: LightCyan
  error_border: Red
  error_text: LightRed
  hint: Yellow
  hovered: Magenta
  inactive: Gray
  playbar_background: Black
  playbar_progress: LightCyan
  playbar_progress_text: Cyan
  playbar_text: White
  selected: LightCyan
  text: 255, 255, 255
  background: Reset
  header: White
  highlighted_lyrics: 0, 200, 200
